resultsdb/controllers/api_v2.py
# Copyright 2013-2016, Red Hat, Inc
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Authors:
#   Josef Skladanka <jskladan@redhat.com>
#   Ralph Bean <rbean@redhat.com>

import re
import uuid

from flask import Blueprint, jsonify, request, url_for
from flask.ext.restful import reqparse

from sqlalchemy.orm import exc as orm_exc
from werkzeug.exceptions import HTTPException


from werkzeug.exceptions import BadRequest as JSONBadRequest

import iso8601

from resultsdb import app, db
from resultsdb.serializers.api_v2 import Serializer
from resultsdb.models.results import Group, Result, Testcase, ResultData
from resultsdb.models.results import RESULT_OUTCOME
from resultsdb.messaging import load_messaging_plugin

QUERY_LIMIT = 20

api = Blueprint('api_v2', __name__)

# TODO: find out why error handler works for 404 but not for 400


@app.errorhandler(400)
def bad_request(error):
    return jsonify({"message": "Bad request"}), 400


@app.errorhandler(404)
def not_found(error):
    return jsonify({"message": "Not found"}), 404

# =============================================================================
#                               GLOBAL VARIABLES
# =============================================================================

RE_PAGE = re.compile(r"([?&])page=([0-9]+)")

# RP contains request parsers (reqparse.RequestParser).
#    Parsers are added in each 'resource section' for better readability
RP = {}

SERIALIZE = Serializer().serialize

# =============================================================================
#                               GLOBAL METHODS
# =============================================================================


def dict_or_string_type(value, *args, **kwargs):
    if args or kwargs:
        raise TypeError("Unexpected arguments")
    if isinstance(value, dict):
        return value
    if isinstance(value, basestring):
        return value
    raise ValueError("Expected dict or string, got %r" % type(value))


def list_or_none_type(value, *args, **kwargs):
    if args or kwargs:
        raise TypeError("Unexpected arguments")
    if isinstance(value, list):
        return value
    if value is None:
        return value
    raise ValueError("Expected list or None, got %r" % type(value))


def pagination(q, page, limit):
    """
    Sets the offset/limit for the DB query.
    limit+1 is purposely set as 'limit' so we can later on decide whether 'next'
    page link should be provided or set to None.
    """
    # pagination offset
    try:
        page = int(page)
        if page > 0:
            offset = page * limit
            q = q.offset(offset)
    except (TypeError, ValueError):
        pass

    q = q.limit(limit + 1)
    return q


def prev_next_urls(data, limit=QUERY_LIMIT):
    global RE_PAGE

    try:
        match = RE_PAGE.findall(request.url)
        flag, page = match[0][0], int(match[0][1])
    except IndexError:  # page not found
        page = None

    prev = None
    next = None
    placeholder = "[!@#$%^&*PLACEHOLDER*&^%$#@!]"

    if page is None:
        if "?" in request.url:
            baseurl = "%s&page=%s" % (request.url, placeholder)
        else:
            baseurl = "%s?page=%s" % (request.url, placeholder)
        page = 0
    else:
        baseurl = RE_PAGE.sub("%spage=%s" % (flag, placeholder), request.url)

    if page > 0:
        prev = baseurl.replace(placeholder, str(page - 1))
    if len(data) > limit:
        next = baseurl.replace(placeholder, str(page + 1))
        data = data[:limit]

    return data, prev, next


def parse_since(since):
    since_start = None
    since_end = None
    if since is not None:
        s = since.split(',')
        since_start = iso8601.parse_date(s[0])
        try:
            since_start = since_start.replace(tzinfo=None)  # we need to strip timezone info
            since_end = iso8601.parse_date(s[1])
            since_end = since_end.replace(tzinfo=None)  # we need to strip timezone info
        # Yes, this library sucks in Exception handling..
        except IndexError:
            pass
        except (TypeError, ValueError, iso8601.iso8601.ParseError):
            raise iso8601.iso8601.ParseError()
    return since_start, since_end


# =============================================================================
#                                      GROUPS
# =============================================================================


RP['get_groups'] = reqparse.RequestParser()
RP['get_groups'].add_argument('page', default=0, type=int, location='args')
RP['get_groups'].add_argument('limit', default=QUERY_LIMIT, type=int, location='args')
RP['get_groups'].add_argument('uuid', default=None, type=str, location='args')
RP['get_groups'].add_argument('description', default=None, type=str, location='args')
RP['get_groups'].add_argument('description:like', default=None, type=str, location='args')
# These two are ignored.  They're present so reqparse isn't confused by JSONP.
RP['get_groups'].add_argument('callback', type=str, location='args')
RP['get_groups'].add_argument('_', type=str, location='args')


@api.route('/groups', methods=['GET'])
def get_groups():
    try:
        args = RP['get_groups'].parse_args()
    except JSONBadRequest as error:
        return jsonify({"message": "Malformed Request"}), error.code
    except HTTPException as error:
        return jsonify(error.data), error.code

    q = db.session.query(Group).order_by(db.desc(Group.id))

    desc_filters = []
    if args['description']:
        for description in args['description'].split(','):
            if not description.strip():
                continue
            desc_filters.append(Group.description == description)
#        desc_filters.append(Group.description.in_(args['description'].split(',')))
    elif args['description:like']:
        for description in args['description:like'].split(','):
            if not description.strip():
                continue
            desc_filters.append(Group.description.like(description.replace("*", "%")))
    if desc_filters:
        q = q.filter(db.or_(*desc_filters))
    print q

    # Filter by uuid
    if args['uuid']:
        q = q.filter(Group.uuid.in_(args['uuid'].split(',')))

    q = pagination(q, args['page'], args['limit'])
    data, prev, next = prev_next_urls(q.all(), args['limit'])

    return jsonify(dict(
        prev=prev,
        next=next,
        data=[SERIALIZE(o) for o in data],
    ))


@api.route('/groups/<group_id>', methods=['GET'])
def get_group(group_id):
    q = Group.query.filter_by(uuid=group_id)
    group = q.first()
    if not group:
        return jsonify({'message': "Group not found"}), 404

    return jsonify(SERIALIZE(group))


RP['create_group'] = reqparse.RequestParser()
RP['create_group'].add_argument('uuid', type=str, default=None, location='json')
RP['create_group'].add_argument('ref_url', type=str, location='json')
RP['create_group'].add_argument('description', type=str, default=None, location='json')


@api.route('/groups', methods=['POST'])
def create_group():
    try:
        args = RP['create_group'].parse_args()
    except JSONBadRequest as error:
        return jsonify({"message": "Malformed Request"}), error.code
    except HTTPException as error:
        return jsonify(error.data), error.code

    if args['uuid']:
        group = Group.query.filter_by(uuid=args['uuid']).first()
        if not group:
            group = Group(uuid=args['uuid'])
    else:
        group = Group(uuid=str(uuid.uuid1()))

    if args['ref_url']:
        group.ref_url = args['ref_url']
    if args['description']:
        group.description = args['description']

    db.session.add(group)
    db.session.commit()

    db.session.add(group)
    return jsonify(SERIALIZE(group)), 201


# =============================================================================
#                                     RESULTS
# =============================================================================

def select_results(since_start=None, since_end=None, outcomes=None, groups=None, testcases=None, testcases_like=None, result_data=None):
    q = db.session.query(Result).order_by(db.desc(Result.submit_time))

    # Time constraints
    if since_start:
        q = q.filter(Result.submit_time >= since_start)
    if since_end:
        q = q.filter(Result.submit_time <= since_end)

    # Filter by outcome
    if outcomes:
        q = q.filter(Result.outcome.in_(outcomes))

    # Filter by group_id
    if groups:
        q = q.filter(Result.groups.any(Group.uuid.in_(groups)))

    # Filter by testcase_name
    filter_by_testcase = []
    if testcases:
        filter_by_testcase.append(Result.testcase_name.in_(testcases))
    if testcases_like:
        for testcase in testcases_like:
            testcase = testcase.replace('*', '%')
            filter_by_testcase.append(Result.testcase_name.like(testcase))
    if filter_by_testcase:
        q = q.filter(db.or_(*filter_by_testcase))

    # Filter by result_data
    if result_data is not None:
        for key, values in result_data.iteritems():
            try:
                key, modifier = key.split(':')
            except ValueError:  # no : in key
                key, modifier = (key, None)

            if modifier == 'like':
                alias = db.aliased(ResultData)

resultsdb/templates/_formhelpers.html
{% macro render_field(field) %}
  <th>{{ field.label }}</th>
  <td>{{ field(**kwargs)|safe }}</td>
  <td>
    {% for error in field.errors %}
       <span style="color: red;">{{error}}</span>
    {% endfor %}
  </td>
{% endmacro %}

<!-- inspired by https://gist.github.com/maximebf/3986659 -->
{% macro form_field(field) %}
    {% set with_label = kwargs.pop('with_label', False) %}

    {% set inline_ = '' %}
    {% if field.type  == 'BooleanField' %}
        <div class="checkbox">
          <label>
            {{ field(**kwargs) }}
            {{ field.label.text|safe }}
          </label>
        </div>


    {% elif field.type == 'RadioField' %}
      {% for subfield in field %}
        <div class="radio">
          <label>
            {{ subfield(**kwargs) }}
            {{ subfield.label.text|safe }}
          </label>
        </div>
      {% endfor %}
    {% else %}
        <div class="form-group {% if field.errors %}has-error{% endif %}">
            {% set placeholder = '' %}
            {% if not with_label %}
                {% set placeholder = field.label.text %}
            {% endif %}

            {% if with_label %}
                <label for="{{ field.id }}">
                    {{ field.label.text }}{% if field.flags.required %} *{% endif %}:
                </label>
            {% endif %}

            {% set class_ = 'form-control' %}
            {% if field.type == 'FileField' %}
                {% set class_ = class_ + ' input-file' %}
            {% endif %}

            {{ field(class_=class_, placeholder=placeholder, **kwargs) }}

            {% if field.errors %}
                <span class="help-block">{{ field.errors|join(', ') }}</span>
            {% endif %}

            {% if field.description %}
                <p class="help-block">{{ field.description|safe }}</p>
            {% endif %}
        </div>
    {% endif %}
{% endmacro %}

resultsdb/templates/index.html
{% extends "layout.html" %}

{% block body %}

API documentation can be found <a href="http://docs.resultsdb.apiary.io/">here</a>.

{% endblock %}

resultsdb/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>{{ title|default('ResultsDB') }}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- Bootstrap -->
      <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
  </head>

  <body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="navbar-brand"><b>ResultsDB</b></span>
        </div>
        <div class="navbar-collapse collapse">

          <ul class="nav navbar-nav">
              <li><a href="{{ url_for('api_v2.get_groups') }}">Jobs</a></li>
              <li><a href="{{ url_for('api_v2.get_results') }}">Results</a></li>
              <li><a href="{{ url_for('api_v2.get_testcases') }}">Testcases</a></li>
          </ul>

<!--         <div class="navbar-right">
             <input type="button" class="btn btn-default navbar-btn" value="Search" onclick="location.href='';">
         </div> -->

        </div><!--/.nav-collapse -->
      </div><!--/.container -->
    </div><!--/.navbar -->

    <div class="container">

    {% for message in get_flashed_messages() %}
      <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}

    {% block body %}
       <h1> My First Flask Application! </h1>
    {% endblock %}

    </div>
   {% block footer %}
      <footer class="footer">
        <div class="container text-right">
          <p class="text-muted">Version: {{app_version}}</p>
        </div>
      </footer>
    {% endblock %}


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

    {% if config['FEDMENU_URL'] is defined %}
    <script src="{{ config['FEDMENU_URL'] }}/js/fedmenu.js"></script>
    <script>
      fedmenu({
        'url': '{{ config["FEDMENU_DATA_URL"] }}',
        'mimeType': 'application/javascript',
        'position': 'bottom-right',
      });
    </script>
    {% endif %}

  </body>
</html>